### ISSUE TITLE
Getting an error when running wal-set

### ISSUE THREAD

**Issue by skluthe** [zzzeyez/pecan#1]
administrator$ bash ~/Library/Application\ Support/Übersicht/widgets/Pecan/wal-set42:48: syntax error: Expected end of line but found identifier. (-2741)

Here is my wal-set script

#!/usr/bin/env bash

sassc --style expanded "$(dirname "$0")/scss/style.scss" > "$(dirname "$0")/style.css" &&
osascript <<EOD
  tell application "Übersicht"
  	refresh widget id "Pecan-background-coffee"
  end tell
EOD

Here's my style.css

/* Pecan is a bar for Ubersicht */
/* Written by Daniel Neemann */

// Import Colors
@import "/Users/administrator/.cache/wal/colors.scss";

:root {

	/* Define your resolution */
	--monitorwidth: 1920px;
	--monitorheight: 1080px;

	/* Choose background colors, ordered from left to right */
	/* Set --bgcenter to "none" to have date's background same as bar */
	--bg: $color0;
	--bgleft: $color1;
	--bgleft2: $color8;
	--bgcenter: $color0;
	--bgright2: $color8;
	--bgright: $color6;

	/* Choose foreground colors */
	--fgleft: $color0;
	--fgleft2: $color1;
	--fgcenter: $color7;
	--fgright2: $color6;
	--fgright: $color0;

	/* Opacity.  Change --opacitycenter to 0 in order to hide date */
	/* --opacity affects --border, so set it to 0 if you would like */
	/* for every widget to appear independent. */
	--opacity: 1;
	--opacitysides: 1;
	--opacitycenter: 1;

	/* Entire bar's outer padding (use --border for space between widgets) */
	--paddingleft: 300px;
	--paddingright: 300px;
	--paddingv: 10px;

	/* Inner-horizontal padding.  --height determines inner-vertical padding */
	--textpadding: 2ch;

	/* Bar's total height including --border and excluding padding */
	--height: 25px;

	/* Mono font recommended (alignment depends on character width) */
	--font: SF Mono, monospace;
	--fontsize: 11px;

	/* Border size.  Also functions as space between widgets, */
	/* so set --opacity to 0 if you want widgets to appear independent */
	--border: 0px;

}

/* Get monitor width */
.screen {
	width: var(--monitorwidth);
	height: var(--monitorheight);
}

/* Bar background */
.background {
	background-color: var(--bg);
	display: block;
	position: absolute;
  	height: var(--height);
	left: 0px;
	right: 0px;
	margin: var(--paddingv) var(--paddingright) var(--paddingv) var(--paddingleft);
	opacity: var(--opacity);
	z-index: -1;
	box-shadow: 0px 2px 8px 2px rgba(0,0,0,0.25);
}

/* Workspace indicator -- far left -- requires ChunkWM */
.left {
	-webkit-font-smoothing: antialiased;
	color: var(--fgleft);
	display: block;
	position: relative;
	background-color: var(--bgleft);
	opacity: var(--opacitysides);
	font: var(--fontsize) var(--font);
	left: var(--paddingleft);
	padding: 0px var(--textpadding);
	margin: calc(var(--paddingv) + var(--border)) var(--border);
	line-height: calc(var(--height) - calc(var(--border) * 2);
}

/* Network bandwidth -- 2nd to left -- requires ifstat */
.left2 {
	background-color: var(--bgleft2);
	opacity: var(--opacitysides);
	color: var(--fgleft2);
	-webkit-font-smoothing: antialiased;
	position: relative;
	display: block;
	font: var(--fontsize) var(--font);
	left: calc(var(--paddingleft) + calc(var(--textpadding) * 2) + 1ch + var(--border));
	padding: 0px var(--textpadding);
	margin: var(--border);
	top: var(--paddingv);
	line-height: calc(var(--height) - calc(var(--border) * 2);
}

/* Date -- third to left -- set --opacitycenter to 0 to hide */
.center {
	color: var(--fgcenter);
	background-color: var(--bgcenter);
	opacity: var(--opacitycenter);
	-webkit-font-smoothing: antialiased;
	position: absolute;
	display: inline-block;
	font: var(--fontsize) var(--font);
	padding: 0px var(--textpadding);
	width: auto;
	left: 50%;
	transform: translate(-50%);
	margin: var(--border);
	line-height:  calc(var(--height) - calc(var(--border) * 2);
	text-align: center;
}

/* This is a container to align the center widget */
.holder {
	background-color: none;
	display: block;
	position: absolute;
  	height: var(--height);
	left: 0px;
	right: 0px;
	margin: var(--paddingv) var(--paddingright) var(--paddingv) var(--paddingleft);
}

/* Battery percentage -- 4th to left */
.right2 {
	-webkit-font-smoothing: antialiased;
	color: var(--fgright2);
 	display: block;
	position: relative;
	background-color: var(--bgright2);
	opacity: var(--opacitysides);
	font: var(--fontsize) var(--font);
	padding: 0px var(--textpadding);
	margin: var(--border);
	top: var(--paddingv);
	float: right;
	right: calc(var(--paddingright) + calc(var(--textpadding) * 2) + 9ch + 2px + calc(var(--border) * 2));
	margin: var(--border);
	line-height:  calc(var(--height) - calc(var(--border) * 2));
}

/* Clock -- 5th to left */
.right {
	-webkit-font-smoothing: antialiased;
	color: var(--fgright);
 	display: block;
	position: relative;
	background-color: var(--bgright);
	opacity: var(--opacitysides);
	font: var(--fontsize) var(--font);
	padding: 0px var(--textpadding);
	margin: var(--border);
	top: var(--paddingv);
	float: right;
	right: var(--paddingright);
	margin-left: auto;
	margin-right: var(--border);
	line-height:  calc(var(--height) - calc(var(--border) * 2);
}

Let me know if you need anything else. Running the latest version of macOS

**Comment by tmeuze** [comment]
I am having the same issue with loading default themes. For whatever reason, escape characters (`...Application\ Support...`) don't work using the `sed` command, nor manually editing the `uber` value in `pecan-style` (file/dir not found), so I set it to `"$HOME/Library/Application Support/Übersicht/widgets"`.

`pecan-style --load fillmore` results in `42:48: syntax error: Expected end of line but found identifier. (-2741)`

Should I open a new issue for this? Thanks!

**Comment by klemenvon** [comment]
I had the same issue but I resolved it through editing the AppleScript. The issue seems to be that Übersicht does not see a widget named "Pecan-background-coffee" and its instead something else like "Pecan-right2-coffee" (The exact widget name can be checked in the Übersicht tray item).

The workaround I found is to simply refresh Übersicht as a whole by doing the following:

Comment out the following code block in either ```wal-set```(line 4) or ```pecan-style```(line 55):
```
osascript <<EOD
    tell application "Übersicht"
        refresh widget id "Pecan-background-coffee"
    end tell
EOD
```
and replace it with:
```
osascript <<EOD
    tell application "Übersicht" to refresh
EOD
```
You only need to modify one as you will only be running this once. Run the modified script and then revert the changed code block back to what was there before.

It is recommended to do this temporarily only (as far as I know running this once, fixes it forever, persisting even after restarting).

The reason I recommend not keeping the workaround AppleScript is because if you refresh every widget every time you run ```wal-set``` or ```pecan-style``` and you use other widgets like Xanthia, the last stored notification is displayed again.

This is unrelated to this issue, but if you find the recurring notifications annoying it can either be fixed by reverting the quick fix proposed earlier or by appending the following two lines to the end of the ```notify-send``` script in Xanthia:
```
sleep 1
> /tmp/notify
```

**Comment by jdkschang** [comment]
@Lakotnik replaced the code with the given instructions, but for me it leads to another bug:
`execution error: The variable refresh is not defined. (-2753)`. 

Curious as to why `pecan-styles` doesn't recognize an Übersicht command

**Comment by klemenvon** [comment]
According to this thread: https://github.com/felixhageloh/uebersicht/issues/290 you may wish to double check that you spell Übersicht correctly in the apple script. 

That thread links to Übersicht documentation on how to correctly input the Ü in scripts and such.

If this isn't the issue, paste in the script you're using and I'll see if I can help.

**Comment by ennation** [comment]
Alternatively, you can just comment out everything in `pecan-style` relating to `refresh` and manually refresh all Übersicht widgets from the menu bar icon. That worked for me.

Lines 36 and 54-60 were all I had to comment out

**Comment by denniswritescode** [comment]
@Eymantia Yea I just removed the body of the whole `refresh` function and put a echo statement reminding myself to refresh Übersicht. So around line 54 in the pecan-style file you'd have this: 
```
refresh(){
	printf "\nYou may need to refresh Übersicht.\n"
}
```

alternatively you can dive in to how to run `osascript` correctly in bash scripts, but that seemed like a rabbit hole that I'd rather not dive into today.

**Comment by zzzeyez** [comment]
i have decided to refresh like so:

```
refresh(){
osascript -e 'tell application "'$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)'" to refresh'
}
```

hopefully this will work more universally.  i do think the issue stems from the Ü character
