### ISSUE TITLE
Disable refresh while customizing

### ISSUE THREAD

**Issue by alextrastero** [zzzeyez/pecan#15]
Hi there, first of all thanks for this project, been a fan of `unixporn` for some time and found this project there.

This is not an issue but more a `how-to`. While the Debug Console is open i'm trying to debug some css, but due to the refresh rates of each `.coffee` the node's keep collapsing making it hard to inspect the css.

Any way around this ?

Thanks!

**Comment by zzzeyez** [comment]
cool thank you !  i actually don't know a way around this!
