### ISSUE TITLE
Loading theme

### ISSUE THREAD

**Issue by zayajf** [zzzeyez/pecan#16]
Hey New to this and I really appreciate the project!

When I try to load the theme im getting this error. 

<img width="572" alt="Screen Shot 2019-04-01 at 3 57 30 PM" src="https://user-images.githubusercontent.com/35379354/55355649-ea0c1a00-5496-11e9-8fc5-89d16ecda3b3.png">

**Comment by zzzeyez** [comment]
hi!  and thank you.  i have fixed this issue.  i believe in your scenario the theme would have loaded and you would just need to manually restart Übersicht yourself.  but i have fixed it regardless
