### ISSUE TITLE
Styles are incorrectly named

### ISSUE THREAD

**Issue by obtuse-whoosh** [zzzeyez/pecan#17]
In the current version as of writing this the css class names within the `*.coffee` files do not match the configured class names in the `style.css` files.

Here's a list of classnames that need updating:
- `background` renamed to `pecanbackground`
- `left` renamed to `pecanworkspace`
- `left2` renamed to `pecannetwork`
- `center` renamed to `pecandate`
- `right` renamed to `pecanclock`
- `right2` renamed to `pecanbattery`

**Comment by obtuse-whoosh** [comment]
I'll submit a PR

**Comment by Reptarsrage** [comment]
@zzzeyez Please review whenever

**Comment by zzzeyez** [comment]
my bad, i use the scss files and overlooked the css files.  i rewrote all the themes and fixed this issue
