### ISSUE TITLE
chunkwm ws error

### ISSUE THREAD

**Issue by Famis** [zzzeyez/pecan#2]
With my chunkwm setup, I get `"chunkc: connection failed! Pecan/scripts/ws: line 15: [: =: unary operator expected chunkc: connection failed!"` after running pecan. I fixed it temporarily by removing: 
```
if exists /usr/local/bin/chunkc ; then
     /usr/local/bin/chunkc tiling::query --desktop id
else

```

&  `fi` from the ws script, but not sure what the nature of the problem is based on the debug error. Maybe something to do with a chunkwm update?

**Comment by klemenvon** [comment]
Try just running the command ```chunkc tiling::query --desktop id``` and see what you get.
