### ISSUE TITLE
Migrating from CoffeeScript to JSX

### ISSUE THREAD

**Issue by tassyguy** [zzzeyez/pecan#21]
I feel like there's a really good opportunity to migrate Pecan from CoffeeScript to JSX format. My main motivation for the migration is Ubersicht's move to the .jsx format. While CoffeeScript is supported at this time, it looks the move is for future versions of widgets to use the JSX format and this would ensure Pecan doesn't get affected if CoffeeScript is eventually depreciated/unsupported. I'm more than happy to lend a hand with converting it to JSX format and assisting with debugging as I love this widget and want to help enhance its feature-set.

**Comment by zzzeyez** [comment]
i want to do this but don't know much about jsx

**Comment by zzzeyez** [comment]
i done did it
