### ISSUE TITLE
Workspace viewer for yabai

### ISSUE THREAD

**Issue by vod3** [zzzeyez/pecan#23]
Since chunkwm is no longer maintained, a worskpace view for its successor [yabai](https://github.com/koekeishiya/yabai ) would be nice. Thanks!

**Comment by zzzeyez** [comment]
i heard it works by default?  idk, i don't plan on leaving mojave + chunk for a bit

**Comment by SultanSGillani** [comment]
I agree with @vod3 this should be the default now over chunkwm. 

Something like this would suffice:

`ps cax | grep yabai > /dev/null
if [ $? -eq 0 ]; then
  /usr/local/bin/yabai -m query --spaces --space  | grep index | cut -f2- -d: | cut -d',' -f1
else
  echo ""
fi
`

**Comment by zzzeyez** [comment]
ok, that's fine with me i suppose.  someone else with have to test it as i do not have `yabai` installed.  if all is well then i will be closing this @SultanSGillani @vod3 

309b69ebd8161ab0c768b381a5425ecc32ac09ce

**Comment by SultanSGillani** [comment]
Sounds good, ty!
