### ISSUE TITLE
How to disable system menubar?

### ISSUE THREAD

**Issue by dortamiguel** [zzzeyez/pecan#27]
I will like to avoid seeing the menubar when the mouse reaches the top of the screen.

Is this possible?

**Comment by naomi-nori** [comment]
As far as I'm aware you can only hide it in system preferences. Honestly I think still being able to access it is probably for the best as so much additional functionality exists in the menubar it that completely disabling it would be a fairly sever handicap, switching connected bluetooth devices, air play, wifi controls, Übersicht itself, application menus. I agree it doesn't look great when it shows up through.
