### ISSUE TITLE
Unrelated question (tmux?)

### ISSUE THREAD

**Issue by Jarvvski** [zzzeyez/pecan#30]
Hey, was wondering how you have your terminal setup in the related screenshot. Is that tmux? If so, how do you have it styled that way? Thanks.

![image](https://user-images.githubusercontent.com/6012840/92705986-3387b680-f365-11ea-99fe-050e7afe6271.png)

**Comment by zzzeyez** [comment]
it's `tmux` and you can look at my settings in my `dots` repo
