### ISSUE TITLE
Conflicting Styles

### ISSUE THREAD

**Issue by dnuzum** [zzzeyez/pecan#4]
I found Ubersicht years ago and use the [Sidebar](https://github.com/Pe8er/Sidebar.Widget) set of widgets. When these are loaded, it pushes the entire Pecan view up the viewport. Not sure if this is to do with block display or what (I avoid front-end work as much as I can...), but is there a way to get other Ubersicht widgets to be ignored in the logic to sit on top of the Pecan background?

Thanks!

**Comment by zzzeyez** [comment]
this can be changed in the widgets' `style.css` files or style sections.  the value you are looking for is `z-index`.  this is a problem with Übersicht itself as it pretty much just operates as a web page on your desktop
