### ISSUE TITLE
Undefined in top left instead of apple logo

### ISSUE THREAD

**Issue by phildev4** [zzzeyez/pecan#40]
Personally I think this might have to do with a missing font. Very well might be my fault. What should I do?

**Comment by codrinMitu** [comment]
You should replace the code in the file with: `echo ""`

**Comment by codrinMitu** [comment]
![Uploading Screenshot 2022-06-12 at 14.17.59.png…]()

**Comment by codrinMitu** [comment]
![Uploading Screenshot 2022-06-12 at 14.17.59.png…]()

**Comment by codrinMitu** [comment]
The file you're supposed to modify is in widgets/pecan/scripts and is named **ws**.

**Comment by codrinMitu** [comment]
You should replace the code in the file with: `echo ""`
