### ISSUE TITLE
Custom Unicode icons for time

### ISSUE THREAD

**Issue by Jarvvski** [zzzeyez/pecan#5]
@zzzeyez I see in your screenshots (as well in Xanthia) that you have different icons, such as the moon or for music playing?

I was wondering how you're using these, and if there's any logic for setting them. Currently the default ✮ is what my clock shows.

I'm asking, because I'm working on pulling the music player from my own [Uber-bar](https://github.com/Jarvvski/uber-bar) into your project here,  but the icon doesn't match the one used in Xanthia:

![alt](https://i.imgur.com/alggtym.png)

**Comment by zzzeyez** [comment]
it's just a unicode moon character like this: ☾

you can change it manually, it's located in `right.coffee`

i am actually reverting back to the moon one right now though, i miss it
