### ISSUE TITLE
How can i hide some of the elements?

### ISSUE THREAD

**Issue by karambaq** [zzzeyez/pecan#6]
Hi, How can i hide some of the elements?
For example I don't need network plugin, how can i hide it?

**Comment by regan-karlewicz** [comment]
You should open your widgets folder for Ubersicht, and navigate inside the Pecan folder. Open up styles.css, and find the element you're looking for (either left1 or left2) and find where it says 
```
display: inline-block;
``` 
and change it to 
```
display: none;
```
