### ISSUE TITLE
Apple logo not showing in left

### ISSUE THREAD

**Issue by nathanielptaylor** [zzzeyez/pecan#7]
I'm not using chunkwm, so there should be an apple logo in place of the window id in left. However, it's just showing a vertical rectangle where the logo should be. Do you know how to fix this? 
edit: just used a unicode apple symbol

**Comment by zzzeyez** [comment]
i temporarily switched it to a power symbol that might not have displayed properly on your screen.   it is now an apple symbol again, so long as chunkwm is not running
