### ISSUE TITLE
Pecan not themed at all

### ISSUE THREAD

**Issue by j0lol** [zzzeyez/pecan#9]
see title
![image](https://user-images.githubusercontent.com/24716467/43277116-eebfa1ea-90fe-11e8-897a-f244b0988247.png)

**Comment by leifniem** [comment]
Hey, how did you solve this ?

**Comment by leifniem** [comment]
Oh i got it @zzzeyez the widgets are missing the left and right classes natively.

**Comment by joselevelsup** [comment]
I'm currently getting this weird look just by switching styles with `pecan-style` command.

**Comment by obtuse-whoosh** [comment]
I'm having this same issue, what was the fix?

**Comment by j0lol** [comment]
sorry, cant remember solution from 9 months ago, should have posted it here
